title: ruby-jp
description:  |
  ruby-jp は Ruby プログラマー同士の交流を目的とした Slack ワークスペースです。参加者の技術レベルに関わらず、質問・相談・情報交換を気軽にできる場を目指しています。

lang: ja
timezone: Asia/Tokyo

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- vendor/

theme: jekyll-theme-cayman

github_username: ruby-jp

twitter:
  card: summary_large_image
  username: ruby-jp

slack_invite_link: https://join.slack.com/t/ruby-jp/shared_invite/zt-1dtwm6asw-nySp8OsdZfKeowNOxKeyGQ
